### ISSUE TITLE
Feature: Add a default crawl limit, warn the user

### ISSUE THREAD

**Issue by fpapado** [accessibility-tools/CI#1]
### Subject of the issue

Something we have discussed when going over accessible-pipeline, was the default page limit.
Having a crawler out there can add load to websites unduly, especially if the user only wants to scan a single page. A limit such as 5 or 20 could work, and would also give users faster results if they are just trying out the tool.

We could add that limit, and warn the user with a message about how to remove it it.

**Comment by jamesrweb** [comment]
I think that limiting the results should be optional personally since if it is a CI tool at heart, it is intended to run over everything by default. I think that flags are good to configure opt-in features and so if there is a limit, should that also not be an opt-in option?

I was also considering options like fragment and query links to avoid by default but kept them as optional things due to SPAs using them relatively often. Overall though I think the limit flag should be opt-in or alternatively we make it so ridiculously high that it would work for everyone like `100000` for example.

Curious to hear your thoughts on this! 👍

**Comment by jamesrweb** [comment]
@fpapado would be cool to hear your thoughts still and perhaps we can discuss next steps more generally in a new and / or this thread?
