### ISSUE TITLE
Setup ESLint

### ISSUE THREAD

**Issue by egor-sorokin** [accessibility-tools/CI#16]
### Subject of the issue
Setup ESLint to unify code style, use best practices to configure ESLint rules

**Comment by egor-sorokin** [comment]
@jamesrweb please let me know if you know a better way to handle code unification

**Comment by jamesrweb** [comment]
Hi @egor-sorokin, I would suggest that we actually skip eslint and use [Standard](https://standardjs.com/) since it requires no configuration and is perfect for the CI process meaning that if a developer uses a different style to the normal one, it is ok because the CI will do the code formatting for them. Here are [the default rules that Standard provides](https://standardjs.com/rules.html).

We can use ESLint also if you like but [the ESLint CLI](https://eslint.org/docs/user-guide/command-line-interface) can be cumbersome and maintaining the configuration might be something we want to avoid, especially across projects. Open to your thoughts on that though.

Overall, I am generally an advocate for pushing code style, test, build and release runs onto the CI/CD process rather that on the developer side since that removes any margin for errors. Again, open to opinion and thoughts on this point!

**Comment by jamesrweb** [comment]
I will work on the CI/CD this week at some point as we discussed, probably on the weekend. My plan is to implement the CI (code style + test specifically) and CD (build + release to NPM specifically). I will make issues for these two areas before I begin to outline what I plan to do and get feedback on those areas before implementation. Overall though I was thinking CI ([Standard](https://standardjs.com/) for the code formatting + [Jest](https://jestjs.io/) for the tests) and CD ([TypeScript](https://www.typescriptlang.org/) for the build process + [NPM CLI](https://docs.npmjs.com/cli-documentation/cli) for the release process). As I said though, I will write other issues regarding this for discussion however.

**Comment by egor-sorokin** [comment]
> I would suggest that we actually skip eslint and use [Standard](https://standardjs.com/) since it requires no configuration and is perfect for the CI process

Agree, sound reasonable

**Comment by jamesrweb** [comment]
See #18 for that topic but otherwise happy to discuss if you have anything in mind here for this issue? If not we can close it and continue the conversation on #18 😄

**Comment by egor-sorokin** [comment]
Sure, I will close it
